[phases.setup]
nixPkgs = ["python3", "python3Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[variables]
PYTHONUNBUFFERED = "1"

[start]
cmd = "python3 -u main.py"
